// const heroNameArray = [
//   "Abaddon",
//   "Alchemist",
//   "Ancient Apparition",
//   "Anti - Mage",
//   "Arc Warden",
//   "Axe",
//   "Bane",
//   "Batrider",
//   "Beastmaster",
//   "Bloodseeker",
//   "Bounty Hunter",
//   "Brewmaster",
//   "Bristleback",
//   "Broodmother",
//   "Centaur Warrunner",
//   "Chaos Knight",
//   "Chen",
//   "Clinkz",
//   "Clockwerk",
//   "Crystal Maiden",
//   "Dark Seer",
//   "Dark Willow",
//   "Dawnbreaker",
//   "Dazzle",
//   "Death Prophet",
//   "Disruptor",
//   "Doom",
//   "Dragon Knight",
//   "Drow Ranger",
//   "Earth Spirit",
//   "Earthshaker",
//   "Elder Titan",
//   "Ember Spirit",
//   "Enchantress",
//   "Enigma",
//   "Faceless Void",
//   "Grimstroke",
//   "Gyrocopter",
//   "Hoodwink",
//   "Huskar",
//   "Invoker",
//   "Io",
//   "Jakiro",
//   "Juggernaut",
//   "Keeper of the Light",
//   "Kunkka",
//   "Legion Commander",
//   "Leshrac",
//   "Lich",
//   "Lifestealer",
//   "Lina",
//   "Lion",
//   "Lone Druid",
//   "Luna",
//   "Lycan",
//   "Magnus",
//   "Marci",
//   "Mars",
//   "Medusa",
//   "Meepo",
//   "Mirana",
//   "Monkey King",
//   "Morphling",
//   "Naga Siren",
//   "Nature 's Prophet",
//   "Necrophos",
//   "Night Stalker",
//   "Nyx Assassin",
//   "Ogre Magi",
//   "Omniknight",
//   "Oracle",
//   "Outworld Destroyer",
//   "Pangolier",
//   "Phantom Assassin",
//   "Phantom Lancer",
//   "Phoenix",
//   "Primal Beast",
//   "Puck",
//   "Pudge",
//   "Pugna",
//   "Queen of Pain",
//   "Razor",
//   "Riki",
//   "Rubick",
//   "Sand King",
//   "Shadow Demon",
//   "Shadow Fiend",
//   "Shadow Shaman",
//   "Silencer",
//   "Skywrath Mage",
//   "Slardar",
//   "Slark",
//   "Snapfire",
//   "Sniper",
//   "Spectre",
//   "Spirit Breaker",
//   "Storm Spirit",
//   "Sven",
//   "Techies",
//   "Templar Assassin",
//   "Terrorblade",
//   "Tidehunter",
//   "Timbersaw",
//   "Tinker",
//   "Tiny",
//   "Treant Protector",
//   "Troll Warlord",
//   "Tusk",
//   "Underlord",
//   "Undying",
//   "Ursa",
//   "Vengeful Spirit",
//   "Venomancer",
//   "Viper",
//   "Visage",
//   "Void Spirit",
//   "Warlock",
//   "Weaver",
//   "Windranger",
//   "Winter Wyvern",
//   "Witch Doctor",
//   "Wraith King",
//   "Zeus",
// ];

const heroMatchUp = [
  { name: "Abaddon", goodMatchUp: [], badMatchup: [] },
  { name: "Alchemist", goodMatchUp: [], badMatchup: [] },
  { name: "Ancient Apparition", goodMatchUp: [], badMatchup: [] },
  { name: "Anti - Mage", goodMatchUp: [], badMatchup: [] },
  { name: "Arc Warden", goodMatchUp: [], badMatchup: [] },
  { name: "Axe", goodMatchUp: [], badMatchup: [] },
  { name: "Bane", goodMatchUp: [], badMatchup: [] },
  { name: "Batrider", goodMatchUp: [], badMatchup: [] },
  { name: "Beastmaster", goodMatchUp: [], badMatchup: [] },
  { name: "Bloodseeker", goodMatchUp: [], badMatchup: [] },
  { name: "Bounty Hunter", goodMatchUp: [], badMatchup: [] },
  { name: "Brewmaster", goodMatchUp: [], badMatchup: [] },
  { name: "Bristleback", goodMatchUp: [], badMatchup: [] },
  { name: "Broodmother", goodMatchUp: [], badMatchup: [] },
  { name: "Centaur Warrunner", goodMatchUp: [], badMatchup: [] },
  { name: "Chaos Knight", goodMatchUp: [], badMatchup: [] },
  { name: "Chen", goodMatchUp: [], badMatchup: [] },
  { name: "Clinkz", goodMatchUp: [], badMatchup: [] },
  { name: "Clockwerk", goodMatchUp: [], badMatchup: [] },
  { name: "Crystal Maiden", goodMatchUp: [], badMatchup: [] },
  { name: "Dark Seer", goodMatchUp: [], badMatchup: [] },
  { name: "Dark Willow", goodMatchUp: [], badMatchup: [] },
  { name: "Dawnbreaker", goodMatchUp: [], badMatchup: [] },
  { name: "Dazzle", goodMatchUp: [], badMatchup: [] },
  { name: "Death Prophet", goodMatchUp: [], badMatchup: [] },
  { name: "Disruptor", goodMatchUp: [], badMatchup: [] },
  { name: "Doom", goodMatchUp: [], badMatchup: [] },
  { name: "Dragon Knight", goodMatchUp: [], badMatchup: [] },
  { name: "Drow Ranger", goodMatchUp: [], badMatchup: [] },
  { name: "Earth Spirit", goodMatchUp: [], badMatchup: [] },
  { name: "Earthshaker", goodMatchUp: [], badMatchup: [] },
  { name: "Elder Titan", goodMatchUp: [], badMatchup: [] },
  { name: "Ember Spirit", goodMatchUp: [], badMatchup: [] },
  { name: "Enchantress", goodMatchUp: [], badMatchup: [] },
  { name: "Enigma", goodMatchUp: [], badMatchup: [] },
  { name: "Faceless Void", goodMatchUp: [], badMatchup: [] },
  { name: "Grimstroke", goodMatchUp: [], badMatchup: [] },
  { name: "Gyrocopter", goodMatchUp: [], badMatchup: [] },
  { name: "Hoodwink", goodMatchUp: [], badMatchup: [] },
  { name: "Huskar", goodMatchUp: [], badMatchup: [] },
  { name: "Invoker", goodMatchUp: [], badMatchup: [] },
  { name: "Io", goodMatchUp: [], badMatchup: [] },
  { name: "Jakiro", goodMatchUp: [], badMatchup: [] },
  { name: "Juggernaut", goodMatchUp: [], badMatchup: [] },
  { name: "Keeper of the Light", goodMatchUp: [], badMatchup: [] },
  { name: "Kunkka", goodMatchUp: [], badMatchup: [] },
  { name: "Legion Commander", goodMatchUp: [], badMatchup: [] },
  { name: "Leshrac", goodMatchUp: [], badMatchup: [] },
  { name: "Lich", goodMatchUp: [], badMatchup: [] },
  { name: "Lifestealer", goodMatchUp: [], badMatchup: [] },
  { name: "Lina", goodMatchUp: [], badMatchup: [] },
  { name: "Lion", goodMatchUp: [], badMatchup: [] },
  { name: "Lone Druid", goodMatchUp: [], badMatchup: [] },
  { name: "Luna", goodMatchUp: [], badMatchup: [] },
  { name: "Lycan", goodMatchUp: [], badMatchup: [] },
  { name: "Magnus", goodMatchUp: [], badMatchup: [] },
  { name: "Marci", goodMatchUp: [], badMatchup: [] },
  { name: "Mars", goodMatchUp: [], badMatchup: [] },
  { name: "Medusa", goodMatchUp: [], badMatchup: [] },
  { name: "Meepo", goodMatchUp: [], badMatchup: [] },
  { name: "Mirana", goodMatchUp: [], badMatchup: [] },
  { name: "Monkey King", goodMatchUp: [], badMatchup: [] },
  { name: "Morphling", goodMatchUp: [], badMatchup: [] },
  { name: "Naga Siren", goodMatchUp: [], badMatchup: [] },
  { name: "Nature 's Prophet", goodMatchUp: [], badMatchup: [] },
  { name: "Necrophos", goodMatchUp: [], badMatchup: [] },
  { name: "Night Stalker", goodMatchUp: [], badMatchup: [] },
  { name: "Nyx Assassin", goodMatchUp: [], badMatchup: [] },
  { name: "Ogre Magi", goodMatchUp: [], badMatchup: [] },
  { name: "Omniknight", goodMatchUp: [], badMatchup: [] },
  { name: "Oracle", goodMatchUp: [], badMatchup: [] },
  { name: "Outworld Destroyer", goodMatchUp: [], badMatchup: [] },
  { name: "Pangolier", goodMatchUp: [], badMatchup: [] },
  { name: "Phantom Assassin", goodMatchUp: [], badMatchup: [] },
  { name: "Phantom Lancer", goodMatchUp: [], badMatchup: [] },
  { name: "Phoenix", goodMatchUp: [], badMatchup: [] },
  { name: "Primal Beast", goodMatchUp: [], badMatchup: [] },
  { name: "Puck", goodMatchUp: [], badMatchup: [] },
  { name: "Pudge", goodMatchUp: [], badMatchup: [] },
  { name: "Pugna", goodMatchUp: [], badMatchup: [] },
  { name: "Queen of Pain", goodMatchUp: [], badMatchup: [] },
  { name: "Razor", goodMatchUp: [], badMatchup: [] },
  { name: "Riki", goodMatchUp: [], badMatchup: [] },
  { name: "Rubick", goodMatchUp: [], badMatchup: [] },
  { name: "Sand King", goodMatchUp: [], badMatchup: [] },
  { name: "Shadow Demon", goodMatchUp: [], badMatchup: [] },
  { name: "Shadow Fiend", goodMatchUp: [], badMatchup: [] },
  { name: "Shadow Shaman", goodMatchUp: [], badMatchup: [] },
  { name: "Silencer", goodMatchUp: [], badMatchup: [] },
  { name: "Skywrath Mage", goodMatchUp: [], badMatchup: [] },
  { name: "Slardar", goodMatchUp: [], badMatchup: [] },
  { name: "Slark", goodMatchUp: [], badMatchup: [] },
  { name: "Snapfire", goodMatchUp: [], badMatchup: [] },
  { name: "Sniper", goodMatchUp: [], badMatchup: [] },
  { name: "Spectre", goodMatchUp: [], badMatchup: [] },
  { name: "Spirit Breaker", goodMatchUp: [], badMatchup: [] },
  { name: "Storm Spirit", goodMatchUp: [], badMatchup: [] },
  { name: "Sven", goodMatchUp: [], badMatchup: [] },
  { name: "Techies", goodMatchUp: [], badMatchup: [] },
  { name: "Templar Assassin", goodMatchUp: [], badMatchup: [] },
  { name: "Terrorblade", goodMatchUp: [], badMatchup: [] },
  { name: "Tidehunter", goodMatchUp: [], badMatchup: [] },
  { name: "Timbersaw", goodMatchUp: [], badMatchup: [] },
  { name: "Tinker", goodMatchUp: [], badMatchup: [] },
  { name: "Tiny", goodMatchUp: [], badMatchup: [] },
  { name: "Treant Protector", goodMatchUp: [], badMatchup: [] },
  { name: "Troll Warlord", goodMatchUp: [], badMatchup: [] },
  { name: "Tusk", goodMatchUp: [], badMatchup: [] },
  { name: "Underlord", goodMatchUp: [], badMatchup: [] },
  { name: "Undying", goodMatchUp: [], badMatchup: [] },
  { name: "Ursa", goodMatchUp: [], badMatchup: [] },
  { name: "Vengeful Spirit", goodMatchUp: [], badMatchup: [] },
  { name: "Venomancer", goodMatchUp: [], badMatchup: [] },
  { name: "Viper", goodMatchUp: [], badMatchup: [] },
  { name: "Visage", goodMatchUp: [], badMatchup: [] },
  { name: "Void Spirit", goodMatchUp: [], badMatchup: [] },
  { name: "Warlock", goodMatchUp: [], badMatchup: [] },
  { name: "Weaver", goodMatchUp: [], badMatchup: [] },
  { name: "Windranger", goodMatchUp: [], badMatchup: [] },
  { name: "Winter Wyvern", goodMatchUp: [], badMatchup: [] },
  { name: "Witch Doctor", goodMatchUp: [], badMatchup: [] },
  { name: "Wraith King", goodMatchUp: [], badMatchup: [] },
  { name: "Zeus", goodMatchUp: [], badMatchup: [] },
];
