// const heroNameArray = [
//   "Abaddon",
//   "Alchemist",
//   "Ancient Apparition",
//   "Anti - Mage",
//   "Arc Warden",
//   "Axe",
//   "Bane",
//   "Batrider",
//   "Beastmaster",
//   "Bloodseeker",
//   "Bounty Hunter",
//   "Brewmaster",
//   "Bristleback",
//   "Broodmother",
//   "Centaur Warrunner",
//   "Chaos Knight",
//   "Chen",
//   "Clinkz",
//   "Clockwerk",
//   "Crystal Maiden",
//   "Dark Seer",
//   "Dark Willow",
//   "Dawnbreaker",
//   "Dazzle",
//   "Death Prophet",
//   "Disruptor",
//   "Doom",
//   "Dragon Knight",
//   "Drow Ranger",
//   "Earth Spirit",
//   "Earthshaker",
//   "Elder Titan",
//   "Ember Spirit",
//   "Enchantress",
//   "Enigma",
//   "Faceless Void",
//   "Grimstroke",
//   "Gyrocopter",
//   "Hoodwink",
//   "Huskar",
//   "Invoker",
//   "Io",
//   "Jakiro",
//   "Juggernaut",
//   "Keeper of the Light",
//   "Kunkka",
//   "Legion Commander",
//   "Leshrac",
//   "Lich",
//   "Lifestealer",
//   "Lina",
//   "Lion",
//   "Lone Druid",
//   "Luna",
//   "Lycan",
//   "Magnus",
//   "Marci",
//   "Mars",
//   "Medusa",
//   "Meepo",
//   "Mirana",
//   "Monkey King",
//   "Morphling",
//   "Naga Siren",
//   "Nature 's Prophet",
//   "Necrophos",
//   "Night Stalker",
//   "Nyx Assassin",
//   "Ogre Magi",
//   "Omniknight",
//   "Oracle",
//   "Outworld Destroyer",
//   "Pangolier",
//   "Phantom Assassin",
//   "Phantom Lancer",
//   "Phoenix",
//   "Primal Beast",
//   "Puck",
//   "Pudge",
//   "Pugna",
//   "Queen of Pain",
//   "Razor",
//   "Riki",
//   "Rubick",
//   "Sand King",
//   "Shadow Demon",
//   "Shadow Fiend",
//   "Shadow Shaman",
//   "Silencer",
//   "Skywrath Mage",
//   "Slardar",
//   "Slark",
//   "Snapfire",
//   "Sniper",
//   "Spectre",
//   "Spirit Breaker",
//   "Storm Spirit",
//   "Sven",
//   "Techies",
//   "Templar Assassin",
//   "Terrorblade",
//   "Tidehunter",
//   "Timbersaw",
//   "Tinker",
//   "Tiny",
//   "Treant Protector",
//   "Troll Warlord",
//   "Tusk",
//   "Underlord",
//   "Undying",
//   "Ursa",
//   "Vengeful Spirit",
//   "Venomancer",
//   "Viper",
//   "Visage",
//   "Void Spirit",
//   "Warlock",
//   "Weaver",
//   "Windranger",
//   "Winter Wyvern",
//   "Witch Doctor",
//   "Wraith King",
//   "Zeus",
// ];
//
// https://dota2.fandom.com/wiki/Matchups
// Copy heroes from the side into words
// format to string in excel with "'"@"',"

const heroMatchup = [
  {
    name: "Abaddon",
    goodMatchup: [
      "Death Prophet",
      "Mirana",
      "Bane",
      "Batrider",
      "BeastMaster",
      "Chen",
      "Techies",
      "Bloodseeker",
      "Necrophos",
      "Nyx Assassin",
    ],
    badMatchup: [
      "Ancient Apparition",
      "Axe",
      "Brewmaster",
      "Doom",
      "Lina",
      "Outworld Destroyer",
      "Shadow Demon",
    ],
  },
  {
    name: "Alchemist",
    goodMatchup: [
      "Broodmother",
      "Nature's Prophet",
      "Phoenix",
      "Undying",
      "Huskar",
    ],
    badMatchup: [
      "Axe ",
      "Ancient Apparition",
      "Enchantress",
      "Invoker",
      "Kunkka",
      "Lifestealer",
      "Necrophos",
      "Slardar",
      "Slark",
      "Ursa",
      "Ember Spirit",
      "Razor",
    ],
  },
  {
    name: "Ancient Apparition",
    goodMatchup: [
      "Abaddon",
      "Alchemist",
      "Chen",
      "Crystal Maiden",
      "Dazzle",
      "Death Prophet",
      "Huskar",
      "Io",
      "Morphling",
      "Snapfire",
      "Winter Wyvern",
    ],
    badMatchup: [
      "Anti-Mage",
      "Brewmaster",
      "Riki",
      "Lycan",
      "Mirana",
      "Oracle",
      "Phantom Lancer",
      "Phoenix",
      "Viper",
      "Void Spirit",
      "Weaver",
    ],
  },
  {
    name: "Anti-Mage",
    goodMatchup: [
      "Ancient Apparition",
      "Abaddon",
      "Arc Warden",
      "Bristleback",
      "Clockwerk",
      "Elder Titan",
      "Medusa",
      "Ogre Magi",
      "Phoenix",
      "Pugna",
      "Rubick",
    ],
    badMatchup: [
      "Axe",
      "Bane",
      "Disruptor",
      "Doom",
      "Grimstroke",
      "Legion Commander",
      "Meepo",
      "Night Stalker",
      "Outworld Destroyer",
      "Phantom Assassin",
      "Puck",
    ],
  },
  {
    name: "Arc Warden",
    goodMatchup: [
      "Legion Commander",
      "Templar Assassin",
      "Mirana",
      "Terrorblade",
      "Phoenix",
      "Sniper",
      "Drow Ranger",
      "Enchantress",
    ],
    badMatchup: [
      "Broodmother",
      "Invoker",
      "Anti-Mage",
      "Axe",
      "Bristleback",
      "Chaos Knight",
      "Meepo",
      "Naga Siren",
      "Riki",
      "Phantom Lancer",
      "Pugna",
    ],
  },
  {
    name: "Axe",
    goodMatchup: [
      "Abaddon",
      "Anti-Mage",
      "Broodmother",
      "Chaos Knight",
      "Dazzle",
      "Huskar",
      "Morphling",
      "Nature's Prophet",
      "Phantom Assassin",
      "Phantom Lancer",
      "Slark",
      "Terrorblade",
      "Troll Warlord",
      "Weaver",
    ],
    badMatchup: [
      "Doom",
      "Jakiro",
      "Necrophos",
      "Night Stalker",
      "Outworld Destroyer",
      "Phoenix",
      "Pugna",
      "Shadow Demon",
      "Timbersaw",
      "Ursa",
      "Venomancer",
      "Viper",
    ],
  },
  { name: "Bane", goodMatchup: [], badMatchup: [] },
  { name: "Batrider", goodMatchup: [], badMatchup: [] },
  { name: "Beastmaster", goodMatchup: [], badMatchup: [] },
  { name: "Bloodseeker", goodMatchup: [], badMatchup: [] },
  { name: "Bounty Hunter", goodMatchup: [], badMatchup: [] },
  { name: "Brewmaster", goodMatchup: [], badMatchup: [] },
  { name: "Bristleback", goodMatchup: [], badMatchup: [] },
  { name: "Broodmother", goodMatchup: [], badMatchup: [] },
  { name: "Centaur Warrunner", goodMatchup: [], badMatchup: [] },
  { name: "Chaos Knight", goodMatchup: [], badMatchup: [] },
  { name: "Chen", goodMatchup: [], badMatchup: [] },
  { name: "Clinkz", goodMatchup: [], badMatchup: [] },
  { name: "Clockwerk", goodMatchup: [], badMatchup: [] },
  { name: "Crystal Maiden", goodMatchup: [], badMatchup: [] },
  { name: "Dark Seer", goodMatchup: [], badMatchup: [] },
  { name: "Dark Willow", goodMatchup: [], badMatchup: [] },
  { name: "Dawnbreaker", goodMatchup: [], badMatchup: [] },
  { name: "Dazzle", goodMatchup: [], badMatchup: [] },
  { name: "Death Prophet", goodMatchup: [], badMatchup: [] },
  { name: "Disruptor", goodMatchup: [], badMatchup: [] },
  { name: "Doom", goodMatchup: [], badMatchup: [] },
  { name: "Dragon Knight", goodMatchup: [], badMatchup: [] },
  { name: "Drow Ranger", goodMatchup: [], badMatchup: [] },
  { name: "Earth Spirit", goodMatchup: [], badMatchup: [] },
  { name: "Earthshaker", goodMatchup: [], badMatchup: [] },
  { name: "Elder Titan", goodMatchup: [], badMatchup: [] },
  { name: "Ember Spirit", goodMatchup: [], badMatchup: [] },
  { name: "Enchantress", goodMatchup: [], badMatchup: [] },
  { name: "Enigma", goodMatchup: [], badMatchup: [] },
  { name: "Faceless Void", goodMatchup: [], badMatchup: [] },
  { name: "Grimstroke", goodMatchup: [], badMatchup: [] },
  { name: "Gyrocopter", goodMatchup: [], badMatchup: [] },
  { name: "Hoodwink", goodMatchup: [], badMatchup: [] },
  { name: "Huskar", goodMatchup: [], badMatchup: [] },
  { name: "Invoker", goodMatchup: [], badMatchup: [] },
  { name: "Io", goodMatchup: [], badMatchup: [] },
  { name: "Jakiro", goodMatchup: [], badMatchup: [] },
  { name: "Juggernaut", goodMatchup: [], badMatchup: [] },
  { name: "Keeper of the Light", goodMatchup: [], badMatchup: [] },
  { name: "Kunkka", goodMatchup: [], badMatchup: [] },
  { name: "Legion Commander", goodMatchup: [], badMatchup: [] },
  { name: "Leshrac", goodMatchup: [], badMatchup: [] },
  { name: "Lich", goodMatchup: [], badMatchup: [] },
  { name: "Lifestealer", goodMatchup: [], badMatchup: [] },
  { name: "Lina", goodMatchup: [], badMatchup: [] },
  { name: "Lion", goodMatchup: [], badMatchup: [] },
  { name: "Lone Druid", goodMatchup: [], badMatchup: [] },
  { name: "Luna", goodMatchup: [], badMatchup: [] },
  { name: "Lycan", goodMatchup: [], badMatchup: [] },
  { name: "Magnus", goodMatchup: [], badMatchup: [] },
  { name: "Marci", goodMatchup: [], badMatchup: [] },
  { name: "Mars", goodMatchup: [], badMatchup: [] },
  { name: "Medusa", goodMatchup: [], badMatchup: [] },
  { name: "Meepo", goodMatchup: [], badMatchup: [] },
  { name: "Mirana", goodMatchup: [], badMatchup: [] },
  { name: "Monkey King", goodMatchup: [], badMatchup: [] },
  { name: "Morphling", goodMatchup: [], badMatchup: [] },
  { name: "Naga Siren", goodMatchup: [], badMatchup: [] },
  { name: "Nature 's Prophet", goodMatchup: [], badMatchup: [] },
  { name: "Necrophos", goodMatchup: [], badMatchup: [] },
  { name: "Night Stalker", goodMatchup: [], badMatchup: [] },
  { name: "Nyx Assassin", goodMatchup: [], badMatchup: [] },
  { name: "Ogre Magi", goodMatchup: [], badMatchup: [] },
  { name: "Omniknight", goodMatchup: [], badMatchup: [] },
  { name: "Oracle", goodMatchup: [], badMatchup: [] },
  { name: "Outworld Destroyer", goodMatchup: [], badMatchup: [] },
  { name: "Pangolier", goodMatchup: [], badMatchup: [] },
  { name: "Phantom Assassin", goodMatchup: [], badMatchup: [] },
  { name: "Phantom Lancer", goodMatchup: [], badMatchup: [] },
  { name: "Phoenix", goodMatchup: [], badMatchup: [] },
  { name: "Primal Beast", goodMatchup: [], badMatchup: [] },
  { name: "Puck", goodMatchup: [], badMatchup: [] },
  { name: "Pudge", goodMatchup: [], badMatchup: [] },
  { name: "Pugna", goodMatchup: [], badMatchup: [] },
  { name: "Queen of Pain", goodMatchup: [], badMatchup: [] },
  { name: "Razor", goodMatchup: [], badMatchup: [] },
  { name: "Riki", goodMatchup: [], badMatchup: [] },
  { name: "Rubick", goodMatchup: [], badMatchup: [] },
  { name: "Sand King", goodMatchup: [], badMatchup: [] },
  { name: "Shadow Demon", goodMatchup: [], badMatchup: [] },
  { name: "Shadow Fiend", goodMatchup: [], badMatchup: [] },
  { name: "Shadow Shaman", goodMatchup: [], badMatchup: [] },
  { name: "Silencer", goodMatchup: [], badMatchup: [] },
  { name: "Skywrath Mage", goodMatchup: [], badMatchup: [] },
  { name: "Slardar", goodMatchup: [], badMatchup: [] },
  { name: "Slark", goodMatchup: [], badMatchup: [] },
  { name: "Snapfire", goodMatchup: [], badMatchup: [] },
  { name: "Sniper", goodMatchup: [], badMatchup: [] },
  { name: "Spectre", goodMatchup: [], badMatchup: [] },
  { name: "Spirit Breaker", goodMatchup: [], badMatchup: [] },
  { name: "Storm Spirit", goodMatchup: [], badMatchup: [] },
  { name: "Sven", goodMatchup: [], badMatchup: [] },
  { name: "Techies", goodMatchup: [], badMatchup: [] },
  { name: "Templar Assassin", goodMatchup: [], badMatchup: [] },
  { name: "Terrorblade", goodMatchup: [], badMatchup: [] },
  { name: "Tidehunter", goodMatchup: [], badMatchup: [] },
  { name: "Timbersaw", goodMatchup: [], badMatchup: [] },
  { name: "Tinker", goodMatchup: [], badMatchup: [] },
  { name: "Tiny", goodMatchup: [], badMatchup: [] },
  { name: "Treant Protector", goodMatchup: [], badMatchup: [] },
  { name: "Troll Warlord", goodMatchup: [], badMatchup: [] },
  { name: "Tusk", goodMatchup: [], badMatchup: [] },
  { name: "Underlord", goodMatchup: [], badMatchup: [] },
  { name: "Undying", goodMatchup: [], badMatchup: [] },
  { name: "Ursa", goodMatchup: [], badMatchup: [] },
  { name: "Vengeful Spirit", goodMatchup: [], badMatchup: [] },
  { name: "Venomancer", goodMatchup: [], badMatchup: [] },
  { name: "Viper", goodMatchup: [], badMatchup: [] },
  { name: "Visage", goodMatchup: [], badMatchup: [] },
  { name: "Void Spirit", goodMatchup: [], badMatchup: [] },
  { name: "Warlock", goodMatchup: [], badMatchup: [] },
  { name: "Weaver", goodMatchup: [], badMatchup: [] },
  { name: "Windranger", goodMatchup: [], badMatchup: [] },
  { name: "Winter Wyvern", goodMatchup: [], badMatchup: [] },
  { name: "Witch Doctor", goodMatchup: [], badMatchup: [] },
  { name: "Wraith King", goodMatchup: [], badMatchup: [] },
  { name: "Zeus", goodMatchup: [], badMatchup: [] },
];
